# Generated by Django 6.0.1 on 2026-03-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='meet_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
